"""add town to reports

Revision ID: 748fbb5dd06c
Revises: 3f5a15f5b5e4
Create Date: 2026-09-28 12:10:58.917826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748fbb5dd06c'
down_revision = '3f5a15f5b5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('town')

    # ### end Alembic commands ###
