"""add photo fields to reports

Revision ID: 7f699569cd1b
Revises: 748fbb5dd06c
Create Date: 2026-09-30 21:55:47.979004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f699569cd1b'
down_revision = '748fbb5dd06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_mimetype', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('photo_mimetype')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
